spring:
  application:
    name: lj-user
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/lol
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    mode: HTML
  redisson:
    address: redis://localhost:6379

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /ljServer
    username: ckk
    password: ckk
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:/sqlmap/*sqlmap.xml
  typeAliasesPackage: com.ckk.ljuser.entity
  global-config:
    db-config:
      db-type: mysql
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      table-prefix: c_
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 0
      #logic-not-delete-value: 1
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  config: classpath:logback.xml
#  file: my.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
    register-with-eureka: true

prod:
  rootPath: C:/Users/Administrator/Desktop/亿美达